### ISSUE TITLE
ScriptException: Element not defined

### ISSUE THREAD

**Issue by Noki87** [toast-tk/toast-tk-examples#3]
When running WebExampleRunner, the execution fails with the following errors: 

```
Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 5551
Only local connections are allowed.
2016-03-06 09:03:19,298 ERROR co.sy.to.ru.bl.BlockRunnerProvider [main] Element Google.recherche was not defined
javax.script.ScriptException: Element Google.recherche was not defined
    at com.synaptix.toast.runtime.block.TestBlockRunner.buildArgumentList(TestBlockRunner.java:243) ~[toast-tk-runtime-0.1.0.jar:?]
    at com.synaptix.toast.runtime.block.TestBlockRunner.doLocalActionCall(TestBlockRunner.java:214) [toast-tk-runtime-0.1.0.jar:?]
    at com.synaptix.toast.runtime.block.TestBlockRunner.runThroughLocalActionAdapter(TestBlockRunner.java:128) [toast-tk-runtime-0.1.0.jar:?]
    at com.synaptix.toast.runtime.block.TestBlockRunner.invokeActionAdapterAction(TestBlockRunner.java:100) [toast-tk-runtime-0.1.0.jar:?]
    at com.synaptix.toast.runtime.block.TestBlockRunner.run(TestBlockRunner.java:59) [toast-tk-runtime-0.1.0.jar:?]
    at com.synaptix.toast.runtime.block.TestBlockRunner.run(TestBlockRunner.java:45) [toast-tk-runtime-0.1.0.jar:?]
    at com.synaptix.toast.runtime.TestRunner.runTestPageBlocks(TestRunner.java:102) [toast-tk-runtime-0.1.0.jar:?]
    at com.synaptix.toast.runtime.TestRunner.run(TestRunner.java:48) [toast-tk-runtime-0.1.0.jar:?]
    at com.synaptix.toast.runtime.AbstractScenarioRunner.runScript(AbstractScenarioRunner.java:132) [toast-tk-runtime-0.1.0.jar:?]
    at com.synaptix.toast.runtime.AbstractScenarioRunner.runScenario(AbstractScenarioRunner.java:74) [toast-tk-runtime-0.1.0.jar:?]
    at com.synaptix.toast.runtime.AbstractScenarioRunner.run(AbstractScenarioRunner.java:63) [toast-tk-runtime-0.1.0.jar:?]
    at fr.synaptix.toast.examples.test.web.WebExampleRunner.main(WebExampleRunner.java:25) [classes/:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:?]
2016-03-06 09:03:19,310 WARN co.sy.to.ru.bl.BlockRunnerProvider [main] No runner found for : CommentBlock
```

In the report, the second step fails with the message `ScriptException: Element Google.recherche was not defined`

**Comment by skokaina** [comment]
The issue has been fixed within the snapshot, I'll release a new version:
- Web Elements locator
- Toast-tk-selenium-plugin service locator renamed to: com.synaptix.toast.adapter.web.IWebComponentFactory
