### ISSUE TITLE
CIMongoStorageProjectRunner

### ISSUE THREAD

**Issue by fabienmifsud** [toast-tk/toast-tk-examples#8]
Based on Tag 0.1.4, I get a NPE running CIMongoStorageProjectRunner.

java.lang.NullPointerException
	at io.toast.tk.runtime.dao.DAOManager.getProjectByApiKey(DAOManager.java:115)
	at io.toast.tk.runtime.AbstractProjectRunner.testAndStore(AbstractProjectRunner.java:83)
	at io.toast.tk.runtime.AbstractProjectRunner.testAndStore(AbstractProjectRunner.java:78)
	at io.toast.examples.project.CIMongoStorageProjectRunner.main(CIMongoStorageProjectRunner.java:30)

It seems that some "users" need to be inserted in MongoDB before running the test.

How can i handle that issue and make the CIMongoStorageProjectRunnerworking ?

Thank you

**Comment by skokaina** [comment]
Starting from 0.1.4, an ApiKey must be provided to the CIMongoStorageProjectRunner example.
An ApiKey is a token assigned to each user created within the web application.
The CIMongoStorageProjectRunner can use the "test(...)" method instead of the "testAndStore(...)" one. The last one can be called by passing the test plan object_id if your project doesn't require user management.

**Comment by fabienmifsud** [comment]
Hi Sallah, thanks for your reply. 

I need to use the testAndStore method to store results in mongoDb. Is there any data to insert into mongoDb before launching the ProjectRunner ?

Is that always possible to use the toast-tk-engine without the toast-tk-webapp ?

Regards,

**Comment by harnoux** [comment]
If you follow the [wiki ](https://github.com/toast-tk/toast-tk-webapp/wiki/Getting-started)page (Define the environment properties) this should be enough for the MongoDB. Subject to use the toast-tk-webapp.

And you can use only toast-tk-engine + toast-tk-examples to have working examples without the toast-tk-webapp but results wont be saved. Not sure you could store it without the toast-tk-webapp (without coding it for sure), Sallah will confirm!

**Comment by fabienmifsud** [comment]
Hi Hubert, thank you for this information. It was possible to test and store projects plans without the web-app before the 0.14 version. I'll try to follow the wiki to install the environment and see if it can help me.

**Comment by skokaina** [comment]
Hi Fabien,

You can still use the example without the webapp. The AbstractProjectRunner is exposing a "test(...)" method that will store your testplan history without the need for an ApiKey.
We will update the example project with another class Runner to make it self-explanatory.

+update to be done through this issue

**Comment by skokaina** [comment]
New branch pushed: 8-ci-project-mongo-runner
CIMongoNoApiKeyStorageRunner: example using the test plan project id and the test() method

The example is written using a local database instance: localhost:27017/play_db
One might need to run a migration script on the target mongodb instance to:
1) move testplans created in versions prior 0.1.4 to "report.tesplans" collection
2) clear the "projects" collection if you had one before and replace with a new one containing a project document (-> ProjectImpl class for the document attributes)
3) upsert the test plans with a reference to this project

Here's a migration script example:

```sql
var projectName = "Default";
var cursor = db.projects.find({name: projectName})
var myProject = cursor[0];

if(myProject !== undefined){
    //class names will need to be changed approprially for sub collections (report.campaigns, test)
   //the effort is huge, if the history isn't that important, I'd advise to clear the collections and restart from scratch
    db.report.testplans.update({project: {$exists: false}}, 
                       {$set: {project: myProject, className :"io.toast.tk.dao.domain.impl.report.TestPlanImpl"}}, 
                       { upsert: false, multi:true});
}else{
    print("No project found with name: " + projectName);
    print("Please insert one using db.projects.insert() method");
}
```

**Comment by skokaina** [comment]
@fabienmifsud we shall close this issue if you have been able to work it around
